name: Test Coverage
on:
  pull_request:
  push:
    branches:
      - master
      - release/**

      

jobs: 

  split-test-files: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Create a file with all the pkgs
        run: go list ./... > pkgs.txt
      - name: Split pkgs into 4 files
        run: split -n l/4 --additional-suffix=.txt ./pkgs.txt
      # cache multiple
      - uses: actions/cache@v1
        with:
          path: ./xaa.txt
          key: ${{ runner.os }}-${{ github.head_ref }}-aa
      - uses: actions/cache@v1
        with:
          path: ./xab.txt
          key: ${{ runner.os }}-${{ github.head_ref }}-ab
      - uses: actions/cache@v1
        with:
          path: ./xac.txt
          key: ${{ runner.os }}-${{ github.head_ref }}-ac
      - uses: actions/cache@v1
        with:
          path: ./xad.txt
          key: ${{ runner.os }}-${{ github.head_ref }}-ad

  test-coverage-run-1:
    runs-on: ubuntu-latest
    needs: split-test-files
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          make build
      - uses: actions/cache@v1
        with:
          path: ./xaa.txt
          key: ${{ runner.os }}-${{ github.head_ref }}-aa
      - name: test & coverage report creation
        run: |
          cat xaa.txt | xargs go test -mod=readonly -timeout 15m -race -coverprofile=coverage.txt -covermode=atomic
      - uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt
          fail_ci_if_error: true

  test-coverage-run-2:
    runs-on: ubuntu-latest
    needs: split-test-files
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          make build
      - uses: actions/cache@v1
        with:
          path: ./xab.txt
          key: ${{ runner.os }}-${{ github.head_ref }}-ab
      - name: test & coverage report creation
        run: |
          cat xab.txt | xargs go test -mod=readonly -timeout 15m -race -coverprofile=coverage.txt -covermode=atomic
      - uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt
          fail_ci_if_error: true

  test-coverage-run-3:
    runs-on: ubuntu-latest
    needs: split-test-files
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          make build
      - uses: actions/cache@v1
        with:
          path: ./xac.txt
          key: ${{ runner.os }}-${{ github.head_ref }}-ac
      - name: test & coverage report creation
        run: |
          cat xac.txt | xargs go test -mod=readonly -timeout 15m -race -coverprofile=coverage.txt -covermode=atomic
      - uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt
          fail_ci_if_error: true

  test-coverage-run-4:
    runs-on: ubuntu-latest
    needs: split-test-files
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          make build
      - uses: actions/cache@v1
        with:
          path: ./xad.txt
          key: ${{ runner.os }}-${{ github.head_ref }}-ad
      - name: test & coverage report creation
        run: |
          cat xad.txt | xargs go test -mod=readonly -timeout 15m -race -coverprofile=coverage.txt -covermode=atomic
      - uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt
          fail_ci_if_error: true
